version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

    environment:
      - spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/mydb
      - spring.datasource.username=uttu
      - spring.datasource.password=Uttu@2003
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# You don't need to define the db service if PostgreSQL is running on your local machine.
